#Application Configuration
server:
  error:
    include-message: always
    include-binding-errors: always

# ===============================
# DB
# ===============================
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cheiru.mysql.database.azure.com/panda_test?useSSL=true&requireSSL=false&serverTimezone=UTC
    username: ${USER_BD}
    password: ${PASS_BD}

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    org.springframework.security: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: https://service-registry.azurewebsites.net/eureka/

settings:
  cors_origin: http://localhost:4200
  cors_origin_pro: https://gray-bush-0aeb0ca10.1.azurestaticapps.net


