#Application Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: https://service-registry.azurewebsites.net/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-tenant
          uri: lb://service-tenant
          predicates:
            - Path=/tenants/**
        - id: service-staff-test
          uri: lb://service-staff-test
          predicates:
            - Path=/staadmstaffwwf/**
        - id: service-tenant-prueba
          uri: lb://service-tenant-prueba
          predicates:
            - Path=/tenants/**
